#!/usr/bin/env node
// Generates worker/src/kb-data.js from every markdown file under kb/.
// Run automatically by the worker's dev/deploy/test scripts.

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const kbDir = join(root, 'kb');
const outFile = join(root, 'worker', 'src', 'kb-data.js');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return walk(full);
    return name.endsWith('.md') && name !== 'README.md' ? [full] : [];
  });
}

const files = walk(kbDir).sort();
const docs = files.map((f) => ({
  path: relative(kbDir, f),
  text: readFileSync(f, 'utf8'),
}));

writeFileSync(
  outFile,
  '// GENERATED by tools/build-kb.js — do not edit. Source of truth: kb/*.md\n' +
    `export const KB_FILES = ${JSON.stringify(docs, null, 2)};\n`
);
console.log(`kb-data.js: ${docs.length} docs, ${docs.reduce((n, d) => n + d.text.length, 0)} chars`);
