#!/usr/bin/env node
// Generates worker/src/ui-data.js from worker/ui/. The inbox app is written as
// ordinary HTML/CSS/JS files (no escaping inside a giant template string) and
// inlined into a single page here. Run by the worker's dev/deploy/test scripts.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ui = join(root, 'worker', 'ui');
const read = (name) => readFileSync(join(ui, name), 'utf8');

// Function replacers, so "$&"-style sequences in the sources stay literal.
const html = read('admin.html')
  .replace('/*@inline admin.css*/', () => read('admin.css'))
  .replace('/*@inline admin.js*/', () => read('admin.js'));

if (/<\/script>/i.test(read('admin.js'))) throw new Error('admin.js must not contain a closing script tag');

writeFileSync(
  join(root, 'worker', 'src', 'ui-data.js'),
  '// GENERATED by tools/build-ui.js — do not edit. Source of truth: worker/ui/\n' +
    `export const ADMIN_HTML = ${JSON.stringify(html)};\n`
);
console.log(`ui-data.js: admin app ${html.length} chars`);
